### ISSUE TITLE
Error: Cannot read property 'catch' of null

### ISSUE THREAD

**Issue by abbestrov** [webtorrent/webtorrent-hybrid#127]
I got this exception executing the example file node-download.js.
is there any fix for this?

using ubuntu 20.04 with nodejs 16.1.0

thanks in advance.

------------------------------------------------
**full error body:**

at new Peer (/home/abbes/node/uto/node_modules/simple-peer/index.js:129:29)
    at WebSocketTracker._createPeer (/home/abbes/node/uto/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:405:18)
    at generateOffer (/home/abbes/node/uto/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:371:47)
    at WebSocketTracker._generateOffers (/home/abbes/node/uto/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:364:7)
    at WebSocketTracker.announce (/home/abbes/node/uto/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:61:12)
    at Socket.<anonymous> (/home/abbes/node/uto/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:42:14)
    at Object.onceWrapper (node:events:471:28)
    at Socket.emit (node:events:377:35)
    at Socket._handleOpen (/home/abbes/node/uto/node_modules/simple-websocket/index.js:202:10)
    at WebSocket.Socket._ws.onopen (/home/abbes/node/uto/node_modules/simple-websocket/index.js:77:36)

**Comment by DiegoRBaquero** [comment]
Missing a line of the trace, the main one

**Comment by abbestrov** [comment]
Sorry, but I don't understand what do you mean by: "Missing a line of the trace"?
can you be more specific?

and thanks.

**Comment by DiegoRBaquero** [comment]
The first line of the error body is missing, you have the stack trace, but not the error and its message.

**Comment by abbestrov** [comment]
thanks, I've updated it.
