### ISSUE TITLE
`npm i -S webtorrent-hybrid` — error

### ISSUE THREAD

**Issue by nichoth** [webtorrent/webtorrent-hybrid#177]
**What version of this package are you using?**
The latest one in npm. `5.0.2`

**What operating system, Node.js, and npm version?**
Mac OS
Node — v16.16.0

**What happened?**
Type
```
npm i -S webtorrent-hybrid
```

```
npm ERR! code 1
npm ERR! path /Users/nick/code/server/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: node-pre-gyp: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nick/.npm/_logs/2023-03-27T17_04_50_929Z-debug-0.log
```

**What did you expect to happen?**
Expect npm to install `webtorrent-hybrid`

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by nichoth** [comment]
See issue in `wrtc` — https://github.com/node-webrtc/node-webrtc/issues/749

**Comment by jaqarrick** [comment]
I also am unable to install the `webtorrent-hybrid` package
```zsh
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@16.16.0 | darwin | arm64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/carrick/code/current/torrent-project/experiments/node_modules/wrtc/build/Release/wrtc.node" (not found)
node-pre-gyp http GET https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
node-pre-gyp http 404 https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/Users/carrick/code/current/torrent-project/experiments/node_modules/node-pre-gyp/lib/install.js:149:27)
node-pre-gyp ERR! stack     at PassThrough.emit (node:events:539:35)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/Users/carrick/code/current/torrent-project/experiments/node_modules/needle/lib/needle.js:538:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (node:events:642:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:527:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:494:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:527:28)
node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:315:12)
node-pre-gyp ERR! System Darwin 22.4.0
```
