### ISSUE TITLE
Try seed but get error!

### ISSUE THREAD

**Issue by vsystech** [webtorrent/webtorrent-hybrid#75]
Hello, i'm install webtorrent-hybrid

Upload file to my server and try seed.

var WebTorrent = require('../index')

var client = new WebTorrent()

var filePath = '/var/www/html/video.mp4'

console.log('filePath:', filePath)

client.seed(filePath, function (torrent) {
  console.log('torrentId (info hash):', torrent.infoHash)
})

start this file with node seed.js check file on instant.io start downloading 1 sec and stopped. 

What is the problem ? i'm few days ago try working with webtorrent but is hard...

**Comment by vsystech** [comment]
filePath: /var/www/html/video.mp4
torrentId (info hash): 820e190c1f211dd49ae4184c2ae3c008e07f4283

^C/usr/lib/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/src/RTCPeerConnection.js:17
        throw new Error('Cannot create RTCPeerConnection, the electron-webrtc daemon has been closed')
        ^

Error: Cannot create RTCPeerConnection, the electron-webrtc daemon has been closed
    at new RTCPeerConnection (/usr/lib/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/src/RTCPeerConnection.js:17:15)
    at new Peer (/usr/lib/node_modules/webtorrent-hybrid/node_modules/simple-peer/index.js:82:14)
    at WebSocketTracker._createPeer (/usr/lib/node_modules/webtorrent-hybrid/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:422:14)
    at WebSocketTracker._onAnnounceResponse (/usr/lib/node_modules/webtorrent-hybrid/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:279:17)
    at WebSocketTracker._onSocketData (/usr/lib/node_modules/webtorrent-hybrid/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:224:10)
    at Socket.self._onSocketDataBound (/usr/lib/node_modules/webtorrent-hybrid/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:179:10)
    at Socket.emit (events.js:180:13)
    at addChunk (/usr/lib/node_modules/webtorrent-hybrid/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/usr/lib/node_modules/webtorrent-hybrid/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Socket.Readable.push (/usr/lib/node_modules/webtorrent-hybrid/node_modules/readable-stream/lib/_stream_readable.js:245:10)

**Comment by DiegoRBaquero** [comment]
The problem resides in electron-webrtc that for some reason was closed. Which version of node and which OS are you using?

**Comment by vsystech** [comment]
root@debian-2gb-nbg1-dc3-1 ~ # node -v
v9.9.0
root@debian-2gb-nbg1-dc3-1 ~ # npm -v
5.6.0
root@debian-2gb-nbg1-dc3-1 ~ # cat /etc/issue
Debian GNU/Linux 9 \n \l

**Comment by feross** [comment]
I would follow https://github.com/webtorrent/webtorrent-hybrid/issues/76
