### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by norzak** [webtorrent/webtorrent-hybrid#93]
Has anyone hit this install failure?

I simply run "npm install webtorrent-hybrid -g"

└─┬ webtorrent-hybrid@2.1.0 
  └── UNMET PEER DEPENDENCY domexception@^1.0.1

npm WARN wrtc@0.3.5 requires a peer of domexception@^1.0.1 but none was installed.

**Comment by norzak** [comment]
I do not know if it is related but, when I run webtorrent-hybrid, now I get this error

/usr/lib/node_modules/webtorrent-hybrid/node_modules/simple-peer/index.js:282
Peer.prototype.replaceTrack = async function (oldTrack, newTrack, stream) {
                                    ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/index.js:13:14)

**Comment by DiegoRBaquero** [comment]
What's your OS and CPU architecture?

**Comment by norzak** [comment]
Macos 10.13. I believe this is wrtc related though.

**Comment by 7wwtwinkletoes** [comment]
any news about this issue?

**Comment by markandrus** [comment]
Hi, that’s not an installation failure. Installation still succeeds. wrtc will just make use of an optional peerDependency, domexception, when installed. If it’s not installed, no problem.

**Comment by feross** [comment]
Great, thanks for sharing @markandrus. Closing this issue.
